# Generated by Django 2.2 on 2019-04-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutnry', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('longtitude', models.FloatField(default=0)),
                ('house', models.CharField(max_length=255)),
                ('lantitude', models.FloatField(default=0)),
                ('fly_human', models.BooleanField(default=False)),
                ('fly_self', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('information', models.TextField(blank=True)),
                ('time_start', models.TimeField(blank=True)),
                ('time_end', models.TimeField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_weigth', models.FloatField(default=0)),
                ('one_weigth', models.FloatField(default=0)),
                ('all_value', models.FloatField(default=0)),
                ('sibarate', models.FloatField(default=0)),
                ('fly_human', models.BooleanField(default=False)),
                ('fly_self', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutnry', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('longtitude', models.FloatField(default=0)),
                ('house', models.CharField(max_length=255)),
                ('lantitude', models.FloatField(default=0)),
                ('fly_human', models.BooleanField(default=False)),
                ('fly_self', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('energy', models.FloatField(max_length=255)),
                ('operation_mode', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
