# Generated by Django 2.0.13 on 2019-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='maxEnegry',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='energy',
            field=models.FloatField(default=100),
        ),
    ]
