# Generated by Django 2.0.13 on 2019-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190406_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(max_length=255)),
                ('track', models.TextField(default='')),
            ],
        ),
    ]
