# Generated by Django 2.0.13 on 2019-04-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='drone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Drone'),
        ),
    ]
