# Generated by Django 2.0.13 on 2019-04-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutnry', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('longtitude', models.FloatField(default=0)),
                ('house', models.CharField(max_length=255)),
                ('lantitude', models.FloatField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutnry', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('longtitude', models.FloatField(default=0)),
                ('house', models.CharField(max_length=255)),
                ('lantitude', models.FloatField(default=0)),
                ('progress', models.IntegerField(choices=[(1, 'Заказ получен'), (2, 'В пути'), (3, 'Заказ готов к выдаче'), (4, 'Ожидает подтверждения'), (5, 'Заказ доставлен')], max_length=1)),
                ('deliveryTime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('dron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Drone')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
