# Generated by Django 2.0.13 on 2019-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclient',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Заказ получен'), (2, 'В пути'), (3, 'Заказ готов к выдаче'), (4, 'Ожидает подтверждения'), (5, 'Заказ доставлен')], max_length=255),
        ),
    ]
