# Generated by Django 2.0.13 on 2019-04-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190406_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestclient',
            name='dron',
        ),
    ]
