# Generated by Django 2.0.13 on 2019-04-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190406_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclient',
            name='promise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Promise'),
        ),
    ]
