# Generated by Django 2.0.13 on 2019-04-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190406_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclient',
            name='key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestclient',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
